### ISSUE TITLE
Make number of blocks per cycle a const

### ISSUE THREAD

**Issue by utdrmac** [DefinitelyNotAGoat/go-tezos#21]
Throughout the code, there are many "level / 4096" for calculations based on cycle. Alphanet uses 2048 blocks per cycle. If this were changed to a global CONST then a simple adjustment is all that is necessary to make code work on alphanet. Or even changing to a global variable and having a `-alphanet` switch.

**Comment by utdrmac** [comment]
The library should just call `/chains/main/blocks/head/context/constants` at the start. that way whichever node you point to (mainnet, alpha, zero), the calculations are made correctly.

**Comment by DefinitelyNotAGoat** [comment]
That's a great idea, thanks for sharing!

**Comment by utdrmac** [comment]
This has been implemented.
