### ISSUE TITLE
Why are integers strings?

### ISSUE THREAD

**Issue by utdrmac** [DefinitelyNotAGoat/go-tezos#23]
"rewards" are string type. Why? Shouldn't they be int?

**Comment by DefinitelyNotAGoat** [comment]
There's a lot of little weird types like that because of the way the Tezos RPC responds. I think it's annoying too, but the RPC to get rewards uses a string, instead of an int. You'll also notice if you dive into the RPC that this practice isn't always universal, so you have to be careful.
