### ISSUE TITLE
Documentation on using existing wallet for payment

### ISSUE THREAD

**Issue by utdrmac** [DefinitelyNotAGoat/go-tezos#26]
How do I use an existing wallet to send payouts? Or, what is a more secure way of creating a new wallet other than modifying the core library code?

**Comment by DefinitelyNotAGoat** [comment]
Once the library is well rounded, I'd like to have examples in the goDoc, but I'll leave this open until we get to it. Thanks for the suggestion!

**Comment by utdrmac** [comment]
Resolved in #27
