### ISSUE TITLE
make batchSize a export const variable

### ISSUE THREAD

**Issue by zhanglianghui** [DefinitelyNotAGoat/go-tezos#62]
When CreateBatchPayment function be called under certain conditions that **len(payments) > batchSize**, it will return more than one operation ids.
The CreateBatchPayment function caller wants to know the corresponding relationship between **payments** and **operation id**, so it needs to know the specific value of the batchSize parameter.
So we can let **batchSize** a export const variable.

**Comment by zhanglianghui** [comment]
https://github.com/DefinitelyNotAGoat/go-tezos/pull/63

**Comment by DefinitelyNotAGoat** [comment]
Global variables in a library are generally bad. But it's not a bad idea to make it configurable via parameter. Thanks!

**Comment by zhanglianghui** [comment]
> Global variables in a library are generally bad. But it's not a bad idea to make it configurable via parameter. Thanks!

Yes, It makes more sense let the batchSize configurable. Looking forward to the early realization of this.

**Comment by DefinitelyNotAGoat** [comment]
It's a good idea. I did a major release recently, so I will schedule this ticket for the next major release because it will change the function signature.

**Comment by RomarQ** [comment]
@zhanglianghui #84
