### ISSUE TITLE
GetBlockOperationHashesAtLevel() not return all operation hashes but only one

### ISSUE THREAD

**Issue by zhanglianghui** [DefinitelyNotAGoat/go-tezos#65]
alphanet where level=345799, GetBlockOperationHashesAtLevel() only return one opreation hash opAgfDzQbcGogUpXkWxPdjgaHko9oRUS98ZEnbfiXmpEZtuCedH, but from tzscan https://alphanet.tzscan.io/345799 we can got more then one.

**Comment by DefinitelyNotAGoat** [comment]
Will look into it, thanks for reporting!

**Comment by DefinitelyNotAGoat** [comment]
I fixed it with this patch: 
https://github.com/DefinitelyNotAGoat/go-tezos/commit/8ba781ee0092184e2527ff2c7137e0fadce60d53

Marking as resolved, thanks for reporting.
