### ISSUE TITLE
gt.Delegate.GetRewards bug

### ISSUE THREAD

**Issue by zhanglianghui** [DefinitelyNotAGoat/go-tezos#67]
gt.Delegate.GetRewards return rewards "" than let gt.Delegate.GetReport return error, the test for gt.Delegate.GetRewards must check the rewards !=""

for c := 161; c <= 161; c ++ {
		rewards, err := gt.Delegate.GetRewards("tz1SF9wBoBQbFUF13agZ8EgihLCKM54G1ccV", c)
		if rewards == "" || err != nil {
			t.Errorf("cycle %d, rewards:%q, error %s", c, rewards, err)
		}
	}

**Comment by DefinitelyNotAGoat** [comment]
I wouldn't say this is a bug, but it's a good idea. I'll add it in. Thanks @zhanglianghui!

**Comment by DefinitelyNotAGoat** [comment]
Thanks @zhanglianghui, here's the fix: https://github.com/DefinitelyNotAGoat/go-tezos/commit/b0f00da39decb502b0ddeff61554d973081b0231
