### ISSUE TITLE
v2.0.0: CalculatePayments should have a minimum exclusion parameter

### ISSUE THREAD

**Issue by DefinitelyNotAGoat** [DefinitelyNotAGoat/go-tezos#71]
Calculate payments should have a minimum parameter, to only return payments greater than a certain threshold in mutez.

**Comment by RomarQ** [comment]
A fix for this issue was implemented on commit `c059e77b7cf75af0c0cb160adbb38b52c3d8695c`

**Comment by DefinitelyNotAGoat** [comment]
Thanks for mentioning @RomarQ!
