### ISSUE TITLE
Dynamically Allocate Delegate Report Workers

### ISSUE THREAD

**Issue by DefinitelyNotAGoat** [DefinitelyNotAGoat/go-tezos#72]
We should dynamically allocate the number of works needed based of the delegate's size. The tezos node can't handle large delegates, with the amount of workers that's default.

**Comment by RomarQ** [comment]
I agree, with 1032 delegators on zeronet this approach is too heavy and I run out of file descriptors.

Will try to find a way to improve this.

**Comment by RomarQ** [comment]
Ok, from what I could understand the delegate report is doing redundant requests and should be simplified to reduce the bandwidth usage.

With a huge list of delegators, the delegate report takes a really long time and uses a lot of bandwidth, on slow internet connections it can even timeout.

Will try to make a pull request tomorrow to fix this behavior.

**Comment by RomarQ** [comment]
Fixed, preparing a pull request now.
