### ISSUE TITLE
mainnet preApplyOperations Error

### ISSUE THREAD

**Issue by zhanglianghui** [DefinitelyNotAGoat/go-tezos#74]
When call preApplyOperations on mainnet, the request will return error: bad response code 500. 

I don't know whether this api is available on mainnet or not. Can you test on mainet again?

_, err = o.gt.Post("/chains/main/blocks/head/helpers/preapply/operations", string(transfersOp))

**Comment by DefinitelyNotAGoat** [comment]
Hey thanks for reporting, there is actually a preapply operations function written in Go Tezos already, but I'm not sure it's exported. I will check, and export it if not.

**Comment by DefinitelyNotAGoat** [comment]
Sorry I misread the issue. So under my tests with both alphanet and mainnet `preApplyOperations` is working. In my Payman tool, it uses Go Tezos and specifically the function that calls this, and it works. 

What node are you using by chance? If you are using a public one that's likely the reason, if it's a local node I'll need to investigate more.

**Comment by zhanglianghui** [comment]
In my project I call the function CreateBatchPayment and returned with error, since the `o.preApplyOperations(operationContents, edsig, blockHead)` return a un-nil error.

I have try on mainnet with my personal node and public node `https://mainnet.tezrpc.me`, all nodes got the same error.

**Comment by zhanglianghui** [comment]
I am very unlucky got error when push my project on product environment, but all is ok on develop environment with Tezos alphanet node.

**Comment by zhanglianghui** [comment]
Hello ~~~

**Comment by DefinitelyNotAGoat** [comment]
https://github.com/DefinitelyNotAGoat/payman/issues/8#issuecomment-497538400_

**Comment by zhanglianghui** [comment]
This is not a bug, because my account has not been revealed before preapply/inject operations.
`tezos-client reveal key for tz1Sm***your***account**Q`

See  https://tezos.gitlab.io/alphanet/introduction/howtouse.html?highlight=reveal for more detail.
![image](https://user-images.githubusercontent.com/7401455/58927651-ff950d00-8781-11e9-82f1-d539abd3c1ee.png)

**Comment by DefinitelyNotAGoat** [comment]
Thanks @zhanglianghui, closing. This is the thread for future reference to anyone looking: https://github.com/DefinitelyNotAGoat/payman/issues/8
